// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { application } from '../libs/stimulus'


import ChoicesController from './choices_controller'
application.register('choices', ChoicesController)

import HelloController from './hello_controller'
application.register('hello', HelloController)